Repository take-it-14/take-it-backend, pull requests merged in 2025-01, with the labels that each got.

#5 [Feat] : review entity, controller, service, repository 생성 및 기본 설정 추가
  common/src/main/resources/application.properties
  review-service/.gitignore
  review-service/build.gradle
  review-service/src/main/java/com/takeit/review/application/repository/ReviewPhotoRepository.java
  review-service/src/main/java/com/takeit/review/application/repository/ReviewRepository.java
  review-service/src/main/java/com/takeit/review/application/service/ReviewService.java
  review-service/src/main/java/com/takeit/review/domain/entity/Review.java
  review-service/src/main/java/com/takeit/review/domain/entity/ReviewPhoto.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/JpaReviewPhotoRepository.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/JpaReviewRepository.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/ReviewPhotoRepositoryImpl.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/ReviewRepositoryImpl.java
  review-service/src/main/java/com/takeit/review/presentation/controller/ReviewController.java
  review-service/src/main/resources/application.yml
Labels: feat

#21 [Feat] s3 모듈 추가
  s3-service/.gitattributes
  s3-service/.gitignore
  s3-service/build.gradle
  s3-service/gradle/wrapper/gradle-wrapper.jar
  s3-service/gradle/wrapper/gradle-wrapper.properties
  s3-service/gradlew
  s3-service/gradlew.bat
  s3-service/settings.gradle
  s3-service/src/main/java/com/takeit/s3/S3ServiceApplication.java
  s3-service/src/main/java/com/takeit/s3/infrastructure/config/S3Config.java
  s3-service/src/main/java/com/takeit/s3/infrastructure/util/FileUpload.java
  s3-service/src/main/java/com/takeit/s3/infrastructure/util/dto/S3UploadFile.java
  s3-service/src/main/resources/application.yml
  s3-service/src/test/java/com/takeit/s3/S3ServiceApplicationTests.java
  settings.gradle
Labels: feat

#17 [Feat] 사용자/인증 기능 구현
  auth-service/build.gradle
  auth-service/src/main/java/com/takeit/auth/AuthApplication.java
  auth-service/src/main/java/com/takeit/auth/application/dto/AuthResponse.java
  auth-service/src/main/java/com/takeit/auth/application/dto/CreateSellerDto.java
  auth-service/src/main/java/com/takeit/auth/application/dto/CreateUserDto.java
  auth-service/src/main/java/com/takeit/auth/application/dto/UserResponse.java
  auth-service/src/main/java/com/takeit/auth/application/dto/UserRoleResponse.java
  auth-service/src/main/java/com/takeit/auth/application/service/AuthService.java
  auth-service/src/main/java/com/takeit/auth/application/service/UserService.java
  auth-service/src/main/java/com/takeit/auth/domain/entity/SellerInfo.java
  auth-service/src/main/java/com/takeit/auth/domain/entity/SellerInfoStatus.java
  auth-service/src/main/java/com/takeit/auth/domain/entity/User.java
  auth-service/src/main/java/com/takeit/auth/domain/entity/UserRole.java
  auth-service/src/main/java/com/takeit/auth/domain/repository/SellerInfoRepository.java
  auth-service/src/main/java/com/takeit/auth/domain/repository/UserRepository.java
  auth-service/src/main/java/com/takeit/auth/exception/AuthExceptionHandler.java
  auth-service/src/main/java/com/takeit/auth/infrastructure/config/WebSecurityConfig.java
  auth-service/src/main/java/com/takeit/auth/infrastructure/repository/SellerInfoRepositoryImpl.java
  auth-service/src/main/java/com/takeit/auth/infrastructure/repository/UserRepositoryImpl.java
  auth-service/src/main/java/com/takeit/auth/jwt/JwtUtil.java
  auth-service/src/main/java/com/takeit/auth/presentation/controller/AuthController.java
  auth-service/src/main/java/com/takeit/auth/presentation/controller/UserController.java
  auth-service/src/main/java/com/takeit/auth/presentation/request/CustomerSignUpRequest.java
  auth-service/src/main/java/com/takeit/auth/presentation/request/SellerSignUpRequest.java
  auth-service/src/main/java/com/takeit/auth/presentation/request/SignInRequest.java
  auth-service/src/main/resources/application-local.yml
  auth-service/src/main/resources/application.yml
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  gateway/src/main/java/com/takeit/gateway/LocalJwtAuthenticationFilter.java
  gateway/src/main/resources/application.yml
Labels: feat

#25 [Feat] review 목록 조회 및 상세 조회 기능 추가
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  common/src/main/resources/application.yml
  review-service/src/main/java/com/takeit/review/application/dto/ReviewDetailResponse.java
  review-service/src/main/java/com/takeit/review/application/dto/ReviewPageResponse.java
  review-service/src/main/java/com/takeit/review/application/repository/ReviewRepository.java
  review-service/src/main/java/com/takeit/review/application/service/ReviewService.java
  review-service/src/main/java/com/takeit/review/infrastructure/config/JpaConfig.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/JpaReviewRepository.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/ReviewRepositoryImpl.java
  review-service/src/main/java/com/takeit/review/presentation/controller/ReviewController.java
  s3-service/build.gradle
  s3-service/settings.gradle
  s3-service/src/main/java/com/takeit/s3/infrastructure/util/FileUpload.java
  s3-service/src/main/resources/application.yml
Labels: feat

#26 [Feat] review 삭제 기능 추가
  common/src/main/resources/application.properties
  review-service/src/main/java/com/takeit/review/application/repository/ReviewPhotoRepository.java
  review-service/src/main/java/com/takeit/review/application/service/ReviewService.java
  review-service/src/main/java/com/takeit/review/domain/entity/Review.java
  review-service/src/main/java/com/takeit/review/domain/entity/ReviewPhoto.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/JpaReviewPhotoRepository.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/ReviewPhotoRepositoryImpl.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/ReviewRepositoryImpl.java
  review-service/src/main/java/com/takeit/review/presentation/controller/ReviewController.java
Labels: feat

#33 [Feat] coupon init
  coupon-service/build.gradle
  coupon-service/src/main/java/com/takeit/coupon/application/service/CouponService.java
  coupon-service/src/main/java/com/takeit/coupon/domain/entity/Coupon.java
  coupon-service/src/main/java/com/takeit/coupon/domain/entity/UserCoupon.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/CouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/UserCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/domain/type/CouponType.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/CouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/JpaCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/JpaUserCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/UserCouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/CouponController.java
  coupon-service/src/main/resources/application-local.yml
  coupon-service/src/main/resources/application.yml
Labels: feat

#15 feat/#2-delete-favorite
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  favorite-service/src/main/java/com/takeit/favorite/application/service/FavoriteService.java
  favorite-service/src/main/java/com/takeit/favorite/config/FavoriteQueryDslConfig.java
  favorite-service/src/main/java/com/takeit/favorite/domain/entity/Favorite.java
  favorite-service/src/main/java/com/takeit/favorite/domain/repository/FavoriteRepository.java
  favorite-service/src/main/java/com/takeit/favorite/infrastructure/repository/FavoriteJpaRepository.java
  favorite-service/src/main/java/com/takeit/favorite/infrastructure/repository/FavoriteRepositoryImpl.java
  favorite-service/src/main/java/com/takeit/favorite/presentation/controller/FavoriteController.java
Labels: feat

#22 Feat/#2 search favorite
  favorite-service/src/main/java/com/takeit/favorite/application/dto/favorite/FavoriteResponse.java
  favorite-service/src/main/java/com/takeit/favorite/application/service/FavoriteService.java
  favorite-service/src/main/java/com/takeit/favorite/domain/repository/FavoriteRepository.java
  favorite-service/src/main/java/com/takeit/favorite/infrastructure/repository/FavoriteJpaRepository.java
  favorite-service/src/main/java/com/takeit/favorite/infrastructure/repository/FavoriteRepositoryImpl.java
  favorite-service/src/main/java/com/takeit/favorite/presentation/controller/FavoriteController.java
  favorite-service/src/main/resources/application-local.yml
  favorite-service/src/main/resources/application.yml
Labels: feat

#9 [Feat] 주문 생성 기능 구현
  order-service/build.gradle
  order-service/http/order.http
  order-service/src/main/java/com/takeit/order/application/dto/OrderCreateDto.java
  order-service/src/main/java/com/takeit/order/application/dto/OrderCreateResponse.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/domain/entity/Order.java
  order-service/src/main/java/com/takeit/order/domain/enums/OrderStatus.java
  order-service/src/main/java/com/takeit/order/domain/repository/OrderRepository.java
  order-service/src/main/java/com/takeit/order/infrastructure/repository/OrderRepositoryImpl.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderController.java
  order-service/src/main/java/com/takeit/order/presentation/request/OrderCreateRequest.java
  order-service/src/main/resources/application.yml
Labels: feat

#10 [Feat] 주문 조회 기능 구현
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  order-service/http/order.http
  order-service/src/main/java/com/takeit/order/application/dto/OrderDetailResponse.java
  order-service/src/main/java/com/takeit/order/application/dto/OrderListResponse.java
  order-service/src/main/java/com/takeit/order/application/dto/PageResponse.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/domain/enums/OrderStatus.java
  order-service/src/main/java/com/takeit/order/domain/repository/OrderRepository.java
  order-service/src/main/java/com/takeit/order/infrastructure/repository/OrderRepositoryImpl.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderController.java
Labels: feat

#11 [Feat] 주문 수정 기능 구현
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  order-service/http/order.http
  order-service/src/main/java/com/takeit/order/application/dto/OrderResponse.java
  order-service/src/main/java/com/takeit/order/application/dto/OrderUpdateDto.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/domain/entity/Order.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderController.java
  order-service/src/main/java/com/takeit/order/presentation/request/OrderUpdateRequest.java
Labels: feat

#12 [Feat] 주문 상태 변경 기능 구현
  order-service/http/order.http
  order-service/src/main/java/com/takeit/order/application/dto/OrderStatusUpdateDto.java
  order-service/src/main/java/com/takeit/order/application/dto/OrderStatusUpdateResponse.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/domain/entity/Order.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderController.java
  order-service/src/main/java/com/takeit/order/presentation/request/OrderStatusUpdateRequest.java
Labels: feat

#13 [Feat] 주문 취소 기능 구현
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  order-service/http/order.http
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/domain/entity/Order.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderController.java
Labels: feat

#29 [Feat] 사용자 목록 조회 기능 추가
  auth-service/build.gradle
  auth-service/src/main/java/com/takeit/auth/application/dto/UserPageResponse.java
  auth-service/src/main/java/com/takeit/auth/application/service/UserService.java
  auth-service/src/main/java/com/takeit/auth/domain/repository/UserRepository.java
  auth-service/src/main/java/com/takeit/auth/infrastructure/config/QueryDslConfig.java
  auth-service/src/main/java/com/takeit/auth/infrastructure/repository/UserRepositoryImpl.java
  auth-service/src/main/java/com/takeit/auth/presentation/controller/UserController.java
  auth-service/src/main/resources/application-local.yml
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
Labels: feat

#46 Feat: 상품 등록 기능 구현
  product-service/src/main/java/com/takeit/product/ProductApplication.java
  product-service/src/main/java/com/takeit/product/application/dto/CreateProductDto.java
  product-service/src/main/java/com/takeit/product/application/dto/ProductResponse.java
  product-service/src/main/java/com/takeit/product/application/service/ProductService.java
  product-service/src/main/java/com/takeit/product/domain/entity/Product.java
  product-service/src/main/java/com/takeit/product/domain/repository/ProductRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/config/AuditorAwareImpl.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductController.java
  product-service/src/main/java/com/takeit/product/presentation/request/CreateProductRequest.java
Labels: feat

#47 Feat: 상품 수정, 삭제 기능 구현
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  product-service/src/main/java/com/takeit/product/application/dto/ProductResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/UpdateProductDto.java
  product-service/src/main/java/com/takeit/product/application/service/ProductService.java
  product-service/src/main/java/com/takeit/product/domain/entity/Product.java
  product-service/src/main/java/com/takeit/product/domain/repository/ProductRepository.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductController.java
  product-service/src/main/java/com/takeit/product/presentation/request/UpdateProductRequest.java
Labels: feat

#48 Feat: 상품 단건 조회, 목록 조회 기능 구현
  product-service/src/main/java/com/takeit/product/application/dto/ProductDetailResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/ProductPageResponse.java
  product-service/src/main/java/com/takeit/product/application/service/ProductService.java
  product-service/src/main/java/com/takeit/product/domain/repository/ProductRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/ProductRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductController.java
Labels: feat

#20 feat - payment 기본 세팅
  favorite-service/src/main/java/com/takeit/favorite/application/service/FavoriteService.java
  favorite-service/src/main/java/com/takeit/favorite/infrastructure/repository/FavoriteJpaRepository.java
  favorite-service/src/main/java/com/takeit/favorite/infrastructure/repository/FavoriteRepositoryImpl.java
  payment-service/build.gradle
  payment-service/src/main/java/com/takeit/payment/PaymentApplication.java
  payment-service/src/main/java/com/takeit/payment/application/service/PaymentService.java
  payment-service/src/main/java/com/takeit/payment/domain/entity/Payment.java
  payment-service/src/main/java/com/takeit/payment/domain/entity/PaymentStatus.java
  payment-service/src/main/java/com/takeit/payment/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/takeit/payment/exception/PaymentExceptionHandler.java
  payment-service/src/main/java/com/takeit/payment/infrastructure/repository/PaymentJpaRepository.java
  payment-service/src/main/java/com/takeit/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment-service/src/main/java/com/takeit/payment/presentation/controller/PaymentController.java
  payment-service/src/main/resources/application-local.yml
  payment-service/src/main/resources/application.yml
Labels: feat

#30 feat/#16-cancel-toss-payment
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  payment-service/src/main/java/com/takeit/payment/application/dto/payment/CancelTossPaymentDto.java
  payment-service/src/main/java/com/takeit/payment/application/dto/payment/VerifyTossPaymentDto.java
  payment-service/src/main/java/com/takeit/payment/application/service/PaymentService.java
  payment-service/src/main/java/com/takeit/payment/config/PaymentQueryDslConfig.java
  payment-service/src/main/java/com/takeit/payment/domain/entity/Payment.java
  payment-service/src/main/java/com/takeit/payment/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/takeit/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment-service/src/main/java/com/takeit/payment/presentation/controller/PaymentController.java
  payment-service/src/main/java/com/takeit/payment/presentation/request/CancelTossPaymentRequest.java
  payment-service/src/main/java/com/takeit/payment/presentation/request/VerifyTossPaymentRequest.java
Labels: feat

#55 [Feat] 상품 판매 통계 조회
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  product-service/http/productDailyStat.http
  product-service/src/main/java/com/takeit/product/application/dto/ProductDailyStatResponse.java
  product-service/src/main/java/com/takeit/product/application/service/ProductService.java
  product-service/src/main/java/com/takeit/product/domain/entity/ProductDailyStat.java
  product-service/src/main/java/com/takeit/product/domain/repository/ProductDailyStatRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/ProductDailyStatRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductController.java
Labels: feat

#28 feat - 토스 결제 검증 및 결제 생성 구현 & 테스트 완료
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  favorite-service/src/main/java/com/takeit/favorite/infrastructure/repository/FavoriteJpaRepository.java
  payment-service/src/main/java/com/takeit/payment/application/dto/payment/CancelTossPaymentDto.java
  payment-service/src/main/java/com/takeit/payment/application/dto/payment/VerifyTossPaymentDto.java
  payment-service/src/main/java/com/takeit/payment/application/service/PaymentService.java
  payment-service/src/main/java/com/takeit/payment/config/PaymentQueryDslConfig.java
  payment-service/src/main/java/com/takeit/payment/domain/entity/Payment.java
  payment-service/src/main/java/com/takeit/payment/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/takeit/payment/infrastructure/repository/PaymentJpaRepository.java
  payment-service/src/main/java/com/takeit/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment-service/src/main/java/com/takeit/payment/presentation/controller/PaymentController.java
  payment-service/src/main/java/com/takeit/payment/presentation/request/CancelTossPaymentRequest.java
  payment-service/src/main/java/com/takeit/payment/presentation/request/VerifyTossPaymentRequest.java
Labels: feat

#38 feat/#34-create-category
  product-service/src/main/java/com/takeit/product/application/dto/category/CategoryEntityResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/category/CreateCategoryDto.java
  product-service/src/main/java/com/takeit/product/application/service/CategoryService.java
  product-service/src/main/java/com/takeit/product/domain/entity/Category.java
  product-service/src/main/java/com/takeit/product/domain/repository/CategoryRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/category/CategoryJpaRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/category/CategoryRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/presentation/controller/CategoryController.java
  product-service/src/main/java/com/takeit/product/presentation/request/CreateCategoryRequest.java
Labels: feat

#39 feat - 카테고리 수정 개발
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  product-service/src/main/java/com/takeit/product/application/dto/category/UpdateCategoryDto.java
  product-service/src/main/java/com/takeit/product/application/service/CategoryService.java
  product-service/src/main/java/com/takeit/product/domain/entity/Category.java
  product-service/src/main/java/com/takeit/product/domain/repository/CategoryRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/category/CategoryJpaRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/category/CategoryRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/presentation/controller/CategoryController.java
  product-service/src/main/java/com/takeit/product/presentation/request/UpdateCategoryRequest.java
Labels: feat

#35 [Feat] coupon 생성 기능 추가
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  coupon-service/src/main/java/com/takeit/coupon/CouponApplication.java
  coupon-service/src/main/java/com/takeit/coupon/application/dto/CreateCouponResponse.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/CouponService.java
  coupon-service/src/main/java/com/takeit/coupon/domain/entity/Coupon.java
  coupon-service/src/main/java/com/takeit/coupon/domain/entity/UserCoupon.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/CouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/exception/CouponExceptionHandler.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/config/AuditorAwareImpl.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/CouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/CouponController.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/request/CreateCouponRequest.java
Labels: feat

#41 feat/#34-delete-category
  product-service/src/main/java/com/takeit/product/application/service/CategoryService.java
  product-service/src/main/java/com/takeit/product/domain/entity/Category.java
  product-service/src/main/java/com/takeit/product/domain/repository/CategoryRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/category/CategoryRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/presentation/controller/CategoryController.java
Labels: feat

#42 feat/#34-get-category
  product-service/src/main/java/com/takeit/product/application/service/CategoryService.java
  product-service/src/main/java/com/takeit/product/domain/entity/Category.java
  product-service/src/main/java/com/takeit/product/presentation/controller/CategoryController.java
Labels: feat

#43 feat - 카테고리 전체 목록 조회 기능 구현
  product-service/src/main/java/com/takeit/product/application/dto/CategoryResponse.java
  product-service/src/main/java/com/takeit/product/application/service/CategoryService.java
  product-service/src/main/java/com/takeit/product/domain/repository/CategoryRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/category/CategoryRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/presentation/controller/CategoryController.java
Labels: feat

#60 [Feat] 주문 관련 feignClient endpoint 구현
  order-service/build.gradle
  order-service/src/main/java/com/takeit/order/OrderApplication.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderEndPoint.java
  order-service/src/test/java/com/takeit/order/presentation/controller/OrderEndPointTest.java
Labels: feat

#56 [Chore] s3-service 설정 추가
  product-service/build.gradle
  product-service/src/main/java/com/takeit/product/ProductApplication.java
  product-service/src/main/resources/application-local.yml
Labels: feat

#57 [Feat] product 생성 / 수정에 s3 관련 로직 추가 및 삭제에 product photo delete 처리
  product-service/src/main/java/com/takeit/product/application/dto/CreateProductDto.java
  product-service/src/main/java/com/takeit/product/application/dto/ProductDetailResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/ProductResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/UpdateProductDto.java
  product-service/src/main/java/com/takeit/product/application/service/ProductService.java
  product-service/src/main/java/com/takeit/product/domain/entity/Product.java
  product-service/src/main/java/com/takeit/product/domain/entity/ProductPhoto.java
  product-service/src/main/java/com/takeit/product/domain/repository/ProductPhotoRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/JpaProductPhotoRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/ProductPhotoRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/ProductRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/category/CategoryRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/presentation/controller/CategoryController.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductController.java
  product-service/src/main/java/com/takeit/product/presentation/request/CreateProductRequest.java
  product-service/src/main/java/com/takeit/product/presentation/request/UpdateProductRequest.java
Labels: feat

#36 [Feat] coupon 수정 기능 추가
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  coupon-service/src/main/java/com/takeit/coupon/application/dto/UpdateCouponResponse.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/CouponService.java
  coupon-service/src/main/java/com/takeit/coupon/domain/entity/Coupon.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/CouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/UserCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/CouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/JpaCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/JpaUserCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/UserCouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/CouponController.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/request/UpdateCouponRequest.java
Labels: feat

#37 [Feat] 쿠폰 삭제 기능 추가
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/CouponService.java
  coupon-service/src/main/java/com/takeit/coupon/domain/entity/Coupon.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/CouponController.java
  order-service/build.gradle
  order-service/src/main/java/com/takeit/order/OrderApplication.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderEndPoint.java
  order-service/src/test/java/com/takeit/order/presentation/controller/OrderEndPointTest.java
  product-service/build.gradle
  product-service/src/main/java/com/takeit/product/ProductApplication.java
  product-service/src/main/java/com/takeit/product/application/dto/CategoryResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/CreateProductDto.java
  product-service/src/main/java/com/takeit/product/application/dto/ProductDetailResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/ProductResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/UpdateProductDto.java
  product-service/src/main/java/com/takeit/product/application/dto/category/CategoryEntityResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/category/CreateCategoryDto.java
  product-service/src/main/java/com/takeit/product/application/dto/category/UpdateCategoryDto.java
  product-service/src/main/java/com/takeit/product/application/service/CategoryService.java
  product-service/src/main/java/com/takeit/product/application/service/ProductService.java
  product-service/src/main/java/com/takeit/product/domain/entity/Category.java
  product-service/src/main/java/com/takeit/product/domain/entity/Product.java
  product-service/src/main/java/com/takeit/product/domain/entity/ProductPhoto.java
  product-service/src/main/java/com/takeit/product/domain/repository/CategoryRepository.java
  product-service/src/main/java/com/takeit/product/domain/repository/ProductPhotoRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/JpaProductPhotoRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/ProductPhotoRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/ProductRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/category/CategoryJpaRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/category/CategoryRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/presentation/controller/CategoryController.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductController.java
  product-service/src/main/java/com/takeit/product/presentation/request/CreateCategoryRequest.java
  product-service/src/main/java/com/takeit/product/presentation/request/CreateProductRequest.java
  product-service/src/main/java/com/takeit/product/presentation/request/UpdateCategoryRequest.java
  product-service/src/main/java/com/takeit/product/presentation/request/UpdateProductRequest.java
  product-service/src/main/resources/application-local.yml
Labels: feat

#44 [Fix] 리뷰 repository 위치 이동 및 booleanBuilder 에 predicate 추가
  review-service/src/main/java/com/takeit/review/application/service/ReviewService.java
  review-service/src/main/java/com/takeit/review/domain/repository/ReviewPhotoRepository.java
  review-service/src/main/java/com/takeit/review/domain/repository/ReviewRepository.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/ReviewPhotoRepositoryImpl.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/ReviewRepositoryImpl.java
Labels: fix

#45 [Feat] coupon 상세 조회 및 목록 조회 기능 구현
  coupon-service/src/main/java/com/takeit/coupon/application/dto/CouponPageResponse.java
  coupon-service/src/main/java/com/takeit/coupon/application/dto/CouponResponse.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/CouponService.java
  coupon-service/src/main/java/com/takeit/coupon/domain/entity/Coupon.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/CouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/config/JpaConfig.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/CouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/JpaCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/CouponController.java
Labels: feat

#49 [Feat] user coupon 생성 기능 구현
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  coupon-service/src/main/java/com/takeit/coupon/application/dto/CreateUserCouponResponse.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/CouponService.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/UserCouponService.java
  coupon-service/src/main/java/com/takeit/coupon/domain/entity/UserCoupon.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/UserCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/UserCouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/UserCouponController.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/request/CreateUserCouponRequest.java
  gateway/src/main/resources/application.yml
Labels: feat

#50 [Feat] user coupon 삭제 기능 구현
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/UserCouponService.java
  coupon-service/src/main/java/com/takeit/coupon/domain/entity/UserCoupon.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/UserCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/JpaUserCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/UserCouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/UserCouponController.java
Labels: feat

#51 [Feat] user coupon 사용/취소 기능 구현
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  coupon-service/src/main/java/com/takeit/coupon/application/dto/UpdateUserCouponResponse.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/UserCouponService.java
  coupon-service/src/main/java/com/takeit/coupon/domain/entity/UserCoupon.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/UserCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/UserCouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/UserCouponController.java
Labels: feat

#68 [Fix] 주문 entity에 userCoupon 추가
  order-service/http/order.http
  order-service/src/main/java/com/takeit/order/application/dto/OrderCreateDto.java
  order-service/src/main/java/com/takeit/order/application/dto/OrderDetailResponse.java
  order-service/src/main/java/com/takeit/order/application/dto/OrderResponse.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/domain/entity/Order.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderEndPoint.java
  order-service/src/main/java/com/takeit/order/presentation/request/OrderCreateRequest.java
  order-service/src/test/java/com/takeit/order/presentation/controller/OrderEndPointTest.java
Labels: fix

#52 [Feat] user coupon 목록 조회 / 상세 조회 기능 구현
  coupon-service/src/main/java/com/takeit/coupon/application/dto/UserCouponPageResponse.java
  coupon-service/src/main/java/com/takeit/coupon/application/dto/UserCouponResponse.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/UserCouponService.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/UserCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/UserCouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/UserCouponController.java
Labels: feat

#71 feat - product UUID 로 Product 조회 기능 구현
  product-service/src/main/java/com/takeit/product/application/dto/ProductEntityResponse.java
  product-service/src/main/java/com/takeit/product/application/service/ProductService.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductEndPoint.java
Labels: feat

#72 feat/#67-product-ids-to-entities
  product-service/src/main/java/com/takeit/product/application/dto/category/CategoryResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/product/CreateProductDto.java
  product-service/src/main/java/com/takeit/product/application/dto/product/ProductDailyStatResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/product/ProductDetailResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/product/ProductEntityResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/product/ProductPageResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/product/ProductResponse.java
  product-service/src/main/java/com/takeit/product/application/dto/product/UpdateProductDto.java
  product-service/src/main/java/com/takeit/product/application/service/CategoryService.java
  product-service/src/main/java/com/takeit/product/application/service/ProductService.java
  product-service/src/main/java/com/takeit/product/domain/entity/Product.java
  product-service/src/main/java/com/takeit/product/domain/entity/ProductDailyStat.java
  product-service/src/main/java/com/takeit/product/domain/repository/ProductDailyStatRepository.java
  product-service/src/main/java/com/takeit/product/domain/repository/ProductRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/product/ProductDailyStatRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/product/ProductJpaRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/product/ProductRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/productPhoto/JpaProductPhotoRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/productPhoto/ProductPhotoRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/presentation/controller/CategoryController.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductController.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductEndPoint.java
  product-service/src/main/java/com/takeit/product/presentation/request/CreateProductRequest.java
  product-service/src/main/java/com/takeit/product/presentation/request/UpdateProductRequest.java
Labels: feat

#70 [Feat] coupon 관련 FeignClient endpoint 구현
  coupon-service/build.gradle
  coupon-service/src/main/java/com/takeit/coupon/CouponApplication.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/UserCouponService.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/UserCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/JpaUserCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/UserCouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/UserCouponEndPoint.java
Labels: feat

#65 Feat: Auth Feign Endpoint 추가
  auth-service/build.gradle
  auth-service/src/main/java/com/takeit/auth/AuthApplication.java
  auth-service/src/main/java/com/takeit/auth/application/dto/UserAuthResponse.java
  auth-service/src/main/java/com/takeit/auth/application/service/AdminService.java
  auth-service/src/main/java/com/takeit/auth/application/service/AuthService.java
  auth-service/src/main/java/com/takeit/auth/application/service/UserService.java
  auth-service/src/main/java/com/takeit/auth/presentation/controller/AuthController.java
  auth-service/src/main/java/com/takeit/auth/presentation/controller/AuthEndPoint.java
  gateway/src/main/resources/application.yml
Labels: feat

#80 feat/#75-favorite-apply-feign-client
  favorite-service/src/main/java/com/takeit/favorite/FavoriteApplication.java
  favorite-service/src/main/java/com/takeit/favorite/application/dto/favorite/CreateFavoriteDto.java
  favorite-service/src/main/java/com/takeit/favorite/application/dto/product/ProductDto.java
  favorite-service/src/main/java/com/takeit/favorite/application/dto/user/UserDto.java
  favorite-service/src/main/java/com/takeit/favorite/application/service/FavoriteService.java
  favorite-service/src/main/java/com/takeit/favorite/application/service/ProductService.java
  favorite-service/src/main/java/com/takeit/favorite/application/service/UserService.java
  favorite-service/src/main/java/com/takeit/favorite/infrastructure/client/ProductClient.java
  favorite-service/src/main/java/com/takeit/favorite/infrastructure/client/UserClient.java
  favorite-service/src/main/java/com/takeit/favorite/presentation/controller/FavoriteController.java
  favorite-service/src/main/java/com/takeit/favorite/presentation/request/CreateFavoriteRequest.java
  favorite-service/src/main/java/com/takeit/favorite/utils/AccessValidator.java
Labels: feat

#77 [Feat] review, coupon, user coupon http 추가
  coupon-service/http/coupon.http
  coupon-service/http/user-coupon.http
  review-service/http/reivew.http
  review-service/src/main/java/com/takeit/review/application/dto/UpdateReviewResponse.java
  review-service/src/main/java/com/takeit/review/application/service/ReviewService.java
  review-service/src/main/java/com/takeit/review/exception/ReviewExceptionHandler.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/JpaReviewRepository.java
  review-service/src/main/java/com/takeit/review/presentation/request/UpdateReviewRequest.java
  review-service/src/main/resources/application-local.yml
  review-service/src/main/resources/application.yml
Labels: feat, fix

#84 feat - 카테고리id로 entity 가져오는 endpoint 추가
  product-service/src/main/java/com/takeit/product/application/service/CategoryService.java
  product-service/src/main/java/com/takeit/product/presentation/controller/CategoryEndPoint.java
Labels: feat

#85 feat/#76-category-service-apply-feign-clinet
  product-service/src/main/java/com/takeit/product/application/dto/user/UserDto.java
  product-service/src/main/java/com/takeit/product/application/service/CategoryService.java
  product-service/src/main/java/com/takeit/product/application/service/UserService.java
  product-service/src/main/java/com/takeit/product/infrastructure/client/UserClient.java
  product-service/src/main/java/com/takeit/product/presentation/controller/CategoryController.java
Labels: feat

#88 Feat: Auth 서비스 권한 체크 로직 추가
  auth-service/src/main/java/com/takeit/auth/application/service/AdminService.java
  auth-service/src/main/java/com/takeit/auth/application/service/AuthService.java
  auth-service/src/main/java/com/takeit/auth/application/service/UserService.java
  auth-service/src/main/java/com/takeit/auth/domain/entity/User.java
  auth-service/src/main/java/com/takeit/auth/infrastructure/config/AuditorAwareImpl.java
  auth-service/src/main/java/com/takeit/auth/infrastructure/config/SecurityConfig.java
  auth-service/src/main/java/com/takeit/auth/presentation/controller/AdminController.java
  auth-service/src/main/java/com/takeit/auth/presentation/controller/UserController.java
  gateway/src/main/java/com/takeit/gateway/LocalJwtAuthenticationFilter.java
Labels: feat

#91 [Feat] Auth - SellerInfo 반환하는 Feign Endpoint 추가
  auth-service/src/main/java/com/takeit/auth/application/service/UserService.java
  auth-service/src/main/java/com/takeit/auth/domain/repository/SellerInfoRepository.java
  auth-service/src/main/java/com/takeit/auth/presentation/controller/AuthEndPoint.java
Labels: feat

#82 [Feat] Review Service FeignClient 관련 작업 마무리
  review-service/build.gradle
  review-service/src/main/java/com/takeit/review/ReviewApplication.java
  review-service/src/main/java/com/takeit/review/application/dto/ReviewDetailResponse.java
  review-service/src/main/java/com/takeit/review/application/dto/product/ProductDto.java
  review-service/src/main/java/com/takeit/review/application/dto/user/UserDto.java
  review-service/src/main/java/com/takeit/review/application/service/OrderService.java
  review-service/src/main/java/com/takeit/review/application/service/ProductService.java
  review-service/src/main/java/com/takeit/review/application/service/ReviewService.java
  review-service/src/main/java/com/takeit/review/application/service/UserService.java
  review-service/src/main/java/com/takeit/review/domain/entity/Review.java
  review-service/src/main/java/com/takeit/review/infrastructure/client/OrderClient.java
  review-service/src/main/java/com/takeit/review/infrastructure/client/ProductClient.java
  review-service/src/main/java/com/takeit/review/infrastructure/client/UserClient.java
  review-service/src/main/java/com/takeit/review/infrastructure/config/AuditorAwareImpl.java
Labels: feat

#87 [Feat] Coupon Service FeignClient 관련 작업 마무리
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  coupon-service/http/user-coupon.http
  coupon-service/src/main/java/com/takeit/coupon/application/dto/CreateUserCouponResponse.java
  coupon-service/src/main/java/com/takeit/coupon/application/dto/category/CategoryDto.java
  coupon-service/src/main/java/com/takeit/coupon/application/dto/user/UserDto.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/CategoryService.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/CouponService.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/UserCouponService.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/UserService.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/UserCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/client/CategoryClient.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/client/UserClient.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/UserCouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/request/CreateUserCouponRequest.java
Labels: feat

#93 Chore: 전체 서비스 build.gradle 리팩토링
  auth-service/build.gradle
  build.gradle
  common/build.gradle
  coupon-service/build.gradle
  eureka-server/build.gradle
  favorite-service/build.gradle
  gateway/build.gradle
  order-service/build.gradle
  payment-service/build.gradle
  product-service/build.gradle
  review-service/build.gradle
  s3-service/build.gradle
Labels: enhancement

#90 [Feat] 사용자 확인 로직 추가 및 order 서비스 feignClient 적용
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  order-service/src/main/java/com/takeit/order/OrderApplication.java
  order-service/src/main/java/com/takeit/order/application/annotation/RequireRole.java
  order-service/src/main/java/com/takeit/order/application/aspect/RoleCheckAspect.java
  order-service/src/main/java/com/takeit/order/application/dto/order/OrderCreateDto.java
  order-service/src/main/java/com/takeit/order/application/dto/order/OrderDetailResponse.java
  order-service/src/main/java/com/takeit/order/application/dto/order/OrderListResponse.java
  order-service/src/main/java/com/takeit/order/application/dto/order/OrderResponse.java
  order-service/src/main/java/com/takeit/order/application/dto/order/OrderStatusUpdateDto.java
  order-service/src/main/java/com/takeit/order/application/dto/order/OrderStatusUpdateResponse.java
  order-service/src/main/java/com/takeit/order/application/dto/order/OrderUpdateDto.java
  order-service/src/main/java/com/takeit/order/application/dto/product/ProductDto.java
  order-service/src/main/java/com/takeit/order/application/dto/user/UserDto.java
  order-service/src/main/java/com/takeit/order/application/interceptor/UserCheckInterceptor.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/config/AuditorAwareImpl.java
  order-service/src/main/java/com/takeit/order/config/WebConfig.java
  order-service/src/main/java/com/takeit/order/infrastructure/client/CouponClient.java
  order-service/src/main/java/com/takeit/order/infrastructure/client/ProductClient.java
  order-service/src/main/java/com/takeit/order/infrastructure/client/UserClient.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderController.java
  order-service/src/main/java/com/takeit/order/presentation/request/OrderCreateRequest.java
  order-service/src/main/java/com/takeit/order/presentation/request/OrderStatusUpdateRequest.java
  order-service/src/main/java/com/takeit/order/presentation/request/OrderUpdateRequest.java
Labels: feat

#94 [Feat] 리뷰 생성 / 수정 / 삭제 시 평점 계산 및 상품 stars 수정
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  coupon-service/http/coupon.http
  order-service/src/main/java/com/takeit/order/application/dto/OrderDto.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderEndPoint.java
  order-service/src/test/java/com/takeit/order/presentation/controller/OrderEndPointTest.java
  product-service/src/main/java/com/takeit/product/application/service/ProductService.java
  product-service/src/main/java/com/takeit/product/domain/entity/Product.java
  product-service/src/main/java/com/takeit/product/domain/repository/ProductRepository.java
  product-service/src/main/java/com/takeit/product/infrastructure/repository/product/ProductRepositoryImpl.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductEndPoint.java
  review-service/build.gradle
  review-service/src/main/java/com/takeit/review/application/dto/order/OrderDto.java
  review-service/src/main/java/com/takeit/review/application/service/OrderService.java
  review-service/src/main/java/com/takeit/review/application/service/ProductService.java
  review-service/src/main/java/com/takeit/review/application/service/ReviewRedisService.java
  review-service/src/main/java/com/takeit/review/application/service/ReviewService.java
  review-service/src/main/java/com/takeit/review/domain/entity/Review.java
  review-service/src/main/java/com/takeit/review/domain/repository/ReviewRepository.java
  review-service/src/main/java/com/takeit/review/infrastructure/client/OrderClient.java
  review-service/src/main/java/com/takeit/review/infrastructure/client/ProductClient.java
  review-service/src/main/java/com/takeit/review/infrastructure/config/RedisConfig.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/JpaReviewRepository.java
  review-service/src/main/java/com/takeit/review/infrastructure/repository/ReviewRepositoryImpl.java
  review-service/src/main/resources/application-local.yml
Labels: feat, fix

#98 feat - usernaem으로 user 받아와서 권한 체크 & seller일 경우 userid로 seller정보 받아와서 체크
  common/src/main/java/com/takeit/common/utils/AccessValidator.java
  product-service/src/main/java/com/takeit/product/application/dto/user/SellerDto.java
  product-service/src/main/java/com/takeit/product/application/service/ProductService.java
  product-service/src/main/java/com/takeit/product/application/service/UserService.java
  product-service/src/main/java/com/takeit/product/infrastructure/client/UserClient.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductController.java
Labels: feat

#99 Feat/#95 dockerfile
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  auth-service/build.gradle
  auth-service/src/main/resources/application-dev.yml
  build.gradle
  build.txt
  common/build.gradle
  common/src/main/resources/application.properties
  coupon-service/build.gradle
  coupon-service/src/main/resources/application-dev.yml
  docker-compose.yml
  eureka-server/build.gradle
  eureka-server/src/main/resources/application-dev.yml
  eureka-server/src/main/resources/application-local.yml
  eureka-server/src/main/resources/application.yml
  favorite-service/build.gradle
  favorite-service/src/main/resources/application-dev.yml
  gateway/build.gradle
  gateway/src/main/resources/application-dev.yml
  gradle.properties
  gradlew
  gradlew.bat
  init-database.sql
  order-service/build.gradle
  order-service/src/main/resources/application-dev.yml
  payment-service/build.gradle
  payment-service/src/main/resources/application-dev.yml
  product-service/build.gradle
  product-service/src/main/java/com/takeit/product/domain/entity/Product.java
  product-service/src/main/resources/application-dev.yml
  review-service/build.gradle
  review-service/src/main/resources/application-dev.yml
  s3-service/build.gradle
  settings.gradle
Labels: enhancement

#101 Chore: actions workflow 추가
  .github/workflows/ci.yml
  .gitignore
Labels: enhancement

#106 [Fix] UserCheckInterceptor 및 주문 생성 로직 버그 해결
  order-service/src/main/java/com/takeit/order/application/interceptor/UserCheckInterceptor.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderController.java
Labels: fix

#110 [Feat] rabbitmq 설정 추가 및 보상 트랜잭션 기능 구현
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  docker-compose.yml
  order-service/build.gradle
  order-service/src/main/java/com/takeit/order/application/dto/product/CancelProduct.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/domain/repository/OrderRepository.java
  order-service/src/main/java/com/takeit/order/infrastructure/config/RabbitMQConfig.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderMessageListener.java
  order-service/src/main/resources/application-dev.yml
  order-service/src/main/resources/application-local.yml
  order-service/src/main/resources/application-prod.yml
  payment-service/build.gradle
  payment-service/src/main/java/com/takeit/payment/application/service/PaymentService.java
  payment-service/src/main/java/com/takeit/payment/infrastructure/config/RabbitMQConfig.java
  payment-service/src/main/resources/application-dev.yml
  payment-service/src/main/resources/application-local.yml
  payment-service/src/main/resources/application-prod.yml
  product-service/build.gradle
  product-service/src/main/java/com/takeit/product/application/dto/product/CancelProduct.java
  product-service/src/main/java/com/takeit/product/application/service/ProductRedisService.java
  product-service/src/main/java/com/takeit/product/infrastructure/config/RabbitMQConfig.java
  product-service/src/main/java/com/takeit/product/infrastructure/config/RedisConfig.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductMessageListener.java
  product-service/src/main/resources/application-dev.yml
  product-service/src/main/resources/application-local.yml
  product-service/src/main/resources/application-prod.yml
  review-service/src/main/resources/application-dev.yml
Labels: feat

#113 [Feat] Redis 기반 주문 정보 저장 기능 구현
  docker-compose.yml
  order-service/build.gradle
  order-service/src/main/java/com/takeit/order/application/dto/order/OrderCacheDto.java
  order-service/src/main/java/com/takeit/order/application/dto/order/OrderCreateResponse.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/application/service/RedisService.java
  order-service/src/main/java/com/takeit/order/infrastructure/config/AuditorAwareImpl.java
  order-service/src/main/java/com/takeit/order/infrastructure/config/RabbitMQConfig.java
  order-service/src/main/java/com/takeit/order/infrastructure/config/RedisConfig.java
  order-service/src/main/java/com/takeit/order/infrastructure/config/WebConfig.java
  order-service/src/main/java/com/takeit/order/infrastructure/redis/RedisKeyExpirationListener.java
  order-service/src/main/java/com/takeit/order/infrastructure/redis/RedisKeyExpirationListenerConfig.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderController.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderMessageProducer.java
  order-service/src/main/resources/application-dev.yml
  order-service/src/main/resources/application-local.yml
  order-service/src/main/resources/application-prod.yml
Labels: feat

#112 feat - lua script를 이용한 재고관리 메서드 작성
  product-service/src/main/java/com/takeit/product/application/service/ProductRedisService.java
  product-service/src/main/java/com/takeit/product/application/service/ProductService.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductEndPoint.java
Labels: feat

#115 [Feat] 결제 성공 시 주문 정보 저장 기능 구현
  order-service/src/main/java/com/takeit/order/application/dto/order/OrderCompleteDto.java
  order-service/src/main/java/com/takeit/order/domain/entity/Order.java
  order-service/src/main/java/com/takeit/order/domain/enums/OrderStatus.java
  order-service/src/main/java/com/takeit/order/infrastructure/config/RabbitMQConfig.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderMessageListener.java
  order-service/src/main/resources/application-dev.yml
  order-service/src/main/resources/application-local.yml
  order-service/src/main/resources/application-prod.yml
  payment-service/src/main/java/com/takeit/payment/application/dto/order/OrderCompleteDto.java
  payment-service/src/main/java/com/takeit/payment/application/service/PaymentService.java
  payment-service/src/main/java/com/takeit/payment/infrastructure/config/RabbitMQConfig.java
  payment-service/src/main/java/com/takeit/payment/presentation/controller/PaymentMessageProducer.java
  payment-service/src/main/resources/application-dev.yml
  payment-service/src/main/resources/application-local.yml
  payment-service/src/main/resources/application-prod.yml
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductMessageListener.java
Labels: feat

#116 [Feat] 쿠폰 사용 취소 message queue 구현 및 fix
  coupon-service/build.gradle
  coupon-service/src/main/java/com/takeit/coupon/application/service/UserCouponService.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/UserCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/UserCouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/CouponMessageListener.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/UserCouponEndPoint.java
  coupon-service/src/main/resources/application-dev.yml
  coupon-service/src/main/resources/application-local.yml
  coupon-service/src/main/resources/application-prod.yml
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/infrastructure/config/RabbitMQConfig.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderMessageProducer.java
  order-service/src/main/resources/application-dev.yml
  order-service/src/main/resources/application-local.yml
  order-service/src/main/resources/application-prod.yml
  payment-service/src/main/java/com/takeit/payment/application/service/PaymentService.java
  payment-service/src/main/java/com/takeit/payment/presentation/controller/PaymentController.java
  product-service/src/main/java/com/takeit/product/infrastructure/config/RabbitMQConfig.java
Labels: feat, fix

#120 feat - product 레디스 데이터를 db에 저장하는 로직추가
  product-service/src/main/java/com/takeit/product/infrastructure/config/RabbitMQConfig.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductMessageListener.java
  product-service/src/main/resources/application-dev.yml
  product-service/src/main/resources/application-local.yml
  product-service/src/main/resources/application-prod.yml
Labels: feat

#121 Feat - Monitoring, Logging 적용
  .github/workflows/ci.yml
  Dockerfile
  auth-service/src/main/java/com/takeit/auth/presentation/controller/AuthController.java
  auth-service/src/main/resources/application-dev.yml
  auth-service/src/main/resources/application-local.yml
  auth-service/src/main/resources/application-prod.yml
  auth-service/src/main/resources/logback-spring.xml
  build.gradle
  coupon-service/src/main/resources/application-dev.yml
  coupon-service/src/main/resources/application-local.yml
  coupon-service/src/main/resources/application-prod.yml
  coupon-service/src/main/resources/logback-spring.xml
  docker-compose-prod.yml
  docker-compose.yml
  eureka-server/src/main/resources/application-dev.yml
  eureka-server/src/main/resources/application-local.yml
  eureka-server/src/main/resources/application-prod.yml
  eureka-server/src/main/resources/application.yml
  eureka-server/src/main/resources/logback-spring.xml
  favorite-service/src/main/resources/application-dev.yml
  favorite-service/src/main/resources/application-local.yml
  favorite-service/src/main/resources/application-prod.yml
  favorite-service/src/main/resources/logback-spring.xml
  gateway/src/main/resources/application-dev.yml
  gateway/src/main/resources/application-local.yml
  gateway/src/main/resources/application-prod.yml
  gateway/src/main/resources/logback-spring.xml
  loki-config.yml
  order-service/src/main/resources/application-dev.yml
  order-service/src/main/resources/application-local.yml
  order-service/src/main/resources/application-prod.yml
  order-service/src/main/resources/logback-spring.xml
  payment-service/src/main/resources/application-dev.yml
  payment-service/src/main/resources/application-local.yml
  payment-service/src/main/resources/application-prod.yml
  payment-service/src/main/resources/logback-spring.xml
  product-service/src/main/resources/application-dev.yml
  product-service/src/main/resources/application-local.yml
  product-service/src/main/resources/application-prod.yml
  product-service/src/main/resources/logback-spring.xml
  prometheus.yml
  promtail-config.yml
  review-service/src/main/resources/application-dev.yml
  review-service/src/main/resources/application-local.yml
  review-service/src/main/resources/application-prod.yml
  review-service/src/main/resources/logback-spring.xml
Labels: enhancement

#123 [Fix] 주문 생성 기능 전체 테스트/리팩토링/버그 수정
  common/src/main/java/com/takeit/common/application/dto/CancelProduct.java
  common/src/main/java/com/takeit/common/application/dto/OrderUuidDto.java
  order-service/src/main/java/com/takeit/order/application/dto/order/OrderCacheDto.java
  order-service/src/main/java/com/takeit/order/application/dto/order/OrderCompleteDto.java
  order-service/src/main/java/com/takeit/order/application/dto/product/CancelProduct.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/application/service/RedisService.java
  order-service/src/main/java/com/takeit/order/infrastructure/client/ProductClient.java
  order-service/src/main/java/com/takeit/order/infrastructure/redis/RedisKeyExpirationListener.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderMessageListener.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderMessageProducer.java
  order-service/src/main/resources/application-dev.yml
  order-service/src/main/resources/application-local.yml
  order-service/src/main/resources/application-prod.yml
  payment-service/src/main/java/com/takeit/payment/application/dto/order/OrderCompleteDto.java
  payment-service/src/main/java/com/takeit/payment/application/service/PaymentService.java
  payment-service/src/main/java/com/takeit/payment/presentation/controller/PaymentMessageProducer.java
  product-service/src/main/java/com/takeit/product/application/dto/product/CancelProduct.java
  product-service/src/main/java/com/takeit/product/application/service/ProductRedisService.java
  product-service/src/main/java/com/takeit/product/infrastructure/config/RabbitMQConfig.java
  product-service/src/main/java/com/takeit/product/presentation/controller/ProductMessageListener.java
  product-service/src/main/resources/application-dev.yml
  product-service/src/main/resources/application-local.yml
Labels: fix

#122 [Feat] 대기열 구현
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  order-service/src/main/java/com/takeit/order/OrderApplication.java
  order-service/src/main/java/com/takeit/order/application/dto/queue/QueueDto.java
  order-service/src/main/java/com/takeit/order/application/scheduler/ActiveTokenScheduler.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/application/service/QueueService.java
  order-service/src/main/java/com/takeit/order/application/service/RedisService.java
  order-service/src/main/java/com/takeit/order/infrastructure/config/AsyncConfig.java
  order-service/src/main/java/com/takeit/order/infrastructure/redis/RedisKeyExpirationListener.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderController.java
  order-service/src/main/java/com/takeit/order/presentation/controller/QueueController.java
  order-service/src/main/resources/application-dev.yml
  order-service/src/main/resources/application-local.yml
  order-service/src/main/resources/application-prod.yml
Labels: feat

#126 feat/login-user-on-redis
  auth-service/build.gradle
  auth-service/src/main/java/com/takeit/auth/application/service/AuthService.java
  auth-service/src/main/java/com/takeit/auth/application/service/UserRedisService.java
  auth-service/src/main/java/com/takeit/auth/application/service/UserService.java
  auth-service/src/main/java/com/takeit/auth/domain/entity/User.java
  auth-service/src/main/java/com/takeit/auth/infrastructure/config/RedisConfig.java
  auth-service/src/main/resources/application-dev.yml
  auth-service/src/main/resources/application-local.yml
  auth-service/src/main/resources/application-prod.yml
  docker-compose-prod.yml
Labels: enhancement, feat

#125 [Feat] 회원가입 시 회원 가입 쿠폰 생성 추가, 주문 생성할 때 쿠폰 사용 시 차감 금액 반환, 배달된 주문에서만 리뷰 생성 가능
  auth-service/src/main/java/com/takeit/auth/application/service/CouponService.java
  auth-service/src/main/java/com/takeit/auth/application/service/UserService.java
  auth-service/src/main/java/com/takeit/auth/infrastructure/client/CouponClient.java
  common/src/main/java/com/takeit/common/application/dto/coupon/UseCouponDto.java
  common/src/main/java/com/takeit/common/application/dto/coupon/UseCouponRequestDto.java
  common/src/main/java/com/takeit/common/exception/ErrorCode.java
  coupon-service/src/main/java/com/takeit/coupon/application/service/UserCouponService.java
  coupon-service/src/main/java/com/takeit/coupon/domain/repository/CouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/CouponRepositoryImpl.java
  coupon-service/src/main/java/com/takeit/coupon/infrastructure/repository/JpaCouponRepository.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/UserCouponEndPoint.java
  order-service/src/main/java/com/takeit/order/application/dto/OrderDto.java
  order-service/src/main/java/com/takeit/order/application/service/OrderService.java
  order-service/src/main/java/com/takeit/order/infrastructure/client/CouponClient.java
  order-service/src/main/java/com/takeit/order/presentation/controller/OrderController.java
  review-service/src/main/java/com/takeit/review/application/dto/order/OrderDto.java
  review-service/src/main/java/com/takeit/review/application/service/ReviewService.java
Labels: feat, fix

#132 Feat/deploy
  .github/workflows/cd.yml
  .gitignore
  copilot/.workspace
  copilot/auth-service/manifest.yml
  copilot/coupon-service/manifest.yml
  copilot/environments/prod/manifest.yml
  copilot/eureka-server/manifest.yml
  copilot/favorite-service/manifest.yml
  copilot/gateway/manifest.yml
  copilot/grafana/manifest.yml
  copilot/loki/manifest.yml
  copilot/order-service/manifest.yml
  copilot/payment-service/manifest.yml
  copilot/product-service/manifest.yml
  copilot/prometheus/manifest.yml
  copilot/promtail/manifest.yml
  copilot/rabbitmq/manifest.yml
  copilot/redis-stack/manifest.yml
  copilot/review-service/manifest.yml
  copilot/zipkin/manifest.yml
  docker-compose-prod.yml
Labels: feat

#131 feat/#129-send-product-open-mail
  auth-service/src/main/java/com/takeit/auth/application/dto/UserAuthResponse.java
  auth-service/src/main/java/com/takeit/auth/application/service/UserService.java
  auth-service/src/main/java/com/takeit/auth/domain/repository/UserRepository.java
  auth-service/src/main/java/com/takeit/auth/presentation/controller/AuthEndPoint.java
  docker-compose-prod.yml
  favorite-service/build.gradle
  favorite-service/src/main/java/com/takeit/favorite/FavoriteApplication.java
  favorite-service/src/main/java/com/takeit/favorite/application/service/EmailService.java
  favorite-service/src/main/java/com/takeit/favorite/application/service/FavoriteService.java
  favorite-service/src/main/java/com/takeit/favorite/application/service/UserService.java
  favorite-service/src/main/java/com/takeit/favorite/domain/repository/FavoriteRepository.java
  favorite-service/src/main/java/com/takeit/favorite/infrastructure/client/UserClient.java
  favorite-service/src/main/java/com/takeit/favorite/infrastructure/repository/FavoriteJpaRepository.java
  favorite-service/src/main/java/com/takeit/favorite/infrastructure/repository/FavoriteRepositoryImpl.java
  favorite-service/src/main/java/com/takeit/favorite/scheduler/SendMail.java
  favorite-service/src/main/resources/application.yml
  product-service/src/main/java/com/takeit/product/application/dto/product/ProductResponse.java
Labels: feat

#143 Feat: 대기열 진입 후 inactive 사용자 처리
  auth-service/src/main/java/com/takeit/auth/infrastructure/client/CouponClient.java
  coupon-service/src/main/java/com/takeit/coupon/presentation/controller/UserCouponEndPoint.java
  order-service/src/main/java/com/takeit/order/application/scheduler/ActiveTokenScheduler.java
  order-service/src/main/java/com/takeit/order/application/service/QueueService.java
  order-service/src/main/java/com/takeit/order/application/service/RedisService.java
  order-service/src/main/java/com/takeit/order/infrastructure/redis/RedisKeyExpirationListener.java
  review-service/src/main/java/com/takeit/review/application/service/ReviewService.java
Labels: feat
